Module5 task1
htmlacademy-php1/2074903-doingsdone-14 pull request #10
Opened 2022-04-26 14:18 UTC by MariOlya

2022-04-27 23:27 UTC, ademaro commented on model.php
> +//Получим из таблицы проектов массив для пользователя с id=2 id, именем проекта и подсчетом задач по этому проекту из таблицы задач
тут должны быть функции для формирования массивов из БД, оформи, плиз

2022-04-27 23:28 UTC, ademaro commented on myfunction.php
> +        return ($count);
чутка с отступами/скобками подправить бы

2022-04-27 23:29 UTC, ademaro commented on templates/main.php
> +        <?php foreach ($projects as $p): ?>
что за экономия на спичках?) `$project` было намного читаемее

2022-04-27 23:30 UTC, ademaro commented on templates/main.php
> +                <a class="main-navigation__list-item-link" href="#"><?= $p['name'] ?></a>
а чего htmlspecialchars убрано? XSS-атаки никуда не денутся..

2022-04-27 23:31 UTC, ademaro requested changes
Давай немного подправим. В целом всё круто, молодец!)

2022-04-28 06:13 UTC, MariOlya commented on templates/main.php
> +                <a class="main-navigation__list-item-link" href="#"><?= $p['name'] ?></a>
Потому что там другой способ проверки в php же, нет? ну, т.е. если мы сделаем, когда появятся вводимые данные, подготовленные выражения, то это же уже не потребуется

2022-04-28 06:14 UTC, MariOlya commented on model.php
> +//Получим из таблицы проектов массив для пользователя с id=2 id, именем проекта и подсчетом задач по этому проекту из таблицы задач
Я добавляла, как было показано на курсе. Где посмотреть о каких функциях ты говоришь?

2022-04-28 09:00 UTC, ademaro commented on model.php
> +//Получим из таблицы проектов массив для пользователя с id=2 id, именем проекта и подсчетом задач по этому проекту из таблицы задач
мы же несколько раз о них говорили)
1) функция получения проектов (например, `get_projects()`)
2) функция получения задач (например, `get_tasks()`)

2022-04-28 09:01 UTC, ademaro commented on templates/main.php
> +                <a class="main-navigation__list-item-link" href="#"><?= $p['name'] ?></a>
ты путаешь sql-injection и xss

2022-04-29 06:26 UTC, ademaro commented on index.php
> +$tasks = get_tasks($con);
👍🏼

2022-04-29 06:27 UTC, ademaro commented on model.php
> +            }
сдвинуть влево нужно + ошибки норм будут отрабатывать?)

2022-04-29 06:28 UTC, ademaro approved these changes
Сейчас стало намного лучше, двигаем дальше

2022-04-29 06:28 UTC, merged